# # This file should contain all the record creation needed to seed the database with its default values.
# # The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
# #
# # Examples:
# #
# #   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
# #   Character.create(name: 'Luke', movie: movies.first)
# lady = Categori.create(category_name: "レディース")
# lady_1 = lady.children.create(category_name: "トップス")
# lady_1.children.create([{category_name: "Tシャツ/カットソー(半袖/袖なし)"},{category_name: "Tシャツ/カットソー(七分/長袖)"},{category_name: "シャツ/ブラウス(半袖/袖なし)"},{category_name: "シャツ/ブラウス(七分/長袖)"},{category_name: "ポロシャツ"},{category_name: "キャミソール"},{category_name: "タンクトップ"},{category_name: "ホルターネック"},{category_name: "ニット/セーター"},{category_name: "チュニック"},{category_name: "カーディガン/ボレロ"},{category_name: "アンサンブル"},{category_name: "ベスト/ジレ"},{category_name: "パーカー"},{category_name: "トレーナー/スウェット"},{category_name: "ベアトップ/チューブトップ"},{category_name: "ジャージ"},{category_name: "その他"}])
# lady_2 = lady.children.create(category_name: "ジャケット/アウター")
# lady_2.children.create([{category_name: "テーラードジャケット"},{category_name: "ノーカラージャケット"},{category_name: "Gジャン/デニムジャケット"},{category_name: "レザージャケット"},{category_name: "ダウンジャケット"},{category_name: "ライダースジャケット"},{category_name: "ミリタリージャケット"},{category_name: "ダウンベスト"},{category_name: "ジャンパー/ブルゾン"},{category_name: "ポンチョ"},{category_name: "ロングコート"},{category_name: "トレンチコート"},{category_name: "ダッフルコート"},{category_name: "ピーコート"},{category_name: "チェスターコート"},{category_name: "モッズコート"},{category_name: "スタジャン"},{category_name: "毛皮/ファーコート"},{category_name: "スプリングコート"},{category_name: "スカジャン"},{category_name: "その他"}])
# lady_3 = lady.children.create(category_name: "パンツ")
# lady_3.children.create([{category_name: "デニム/ジーンズ"},{category_name: "ショートパンツ"},{category_name: "カジュアルパンツ"},{category_name: "ハーフパンツ"},{category_name: "チノパン"},{category_name: "ワークパンツ/カーゴパンツ"},{category_name: "クロップドパンツ"},{category_name: "サロペット/オーバーオール"},{category_name: "オールインワン"},{category_name: "サルエルパンツ"},{category_name: "ガウチョパンツ"},{category_name: "その他"}])
# lady_4 = lady.children.create(category_name: "スカート")
# lady_4.children.create([{category_name: "ミニスカート"},{category_name: "ひざ丈スカート"},{category_name: "ロングスカート"},{category_name: "キュロット"},{category_name: "その他"}])
# lady_5 = lady.children.create(category_name: "ワンピース")
# lady_5.children.create([{category_name: "ミニワンピース"},{category_name: "ひざ丈ワンピース"},{category_name: "ロングワンピース"},{category_name: "その他"}])
# lady_6 = lady.children.create(category_name: "靴")
# lady_6.children.create([{category_name: "ハイヒール/パンプス"},{category_name: "ブーツ"},{category_name: "サンダル"},{category_name: "スニーカー"},{category_name: "ミュール"},{category_name: "モカシン"},{category_name: "ローファー/革靴"},{category_name: "フラットシューズ/バレエシューズ"},{category_name: "長靴/レインシューズ"},{category_name: "その他"}])
# lady_7 = lady.children.create(category_name: "ルームウェア/パジャマ")
# lady_7.children.create([{category_name: "パジャマ"},{category_name: "ルームウェア"}])
# lady_8 = lady.children.create(category_name: "レッグウェア")
# lady_8.children.create([{category_name: "ソックス"},{category_name: "スパッツ/レギンス"},{category_name: "ストッキング/タイツ"},{category_name: "レッグウォーマー"},{category_name: "その他"}])
# lady_9 = lady.children.create(category_name: "帽子")
# lady_9.children.create([{category_name: "ニットキャップ/ビーニー"},{category_name: "ハット"},{category_name: "ハンチング/ベレー帽"},{category_name: "キャップ"},{category_name: "キャスケット"},{category_name: "麦わら帽子"},{category_name: "その他"}])
# lady_10 = lady.children.create(category_name: "バッグ")
# lady_10.children.create([{category_name: "ハンドバッグ"},{category_name: "トートバッグ"},{category_name: "エコバッグ"},{category_name: "リュック/バックパック"},{category_name: "ボストンバッグ"},{category_name: "スポーツバッグ"},{category_name: "ショルダーバッグ"},{category_name: "クラッチバッグ"},{category_name: "ポーチ/バニティ"},{category_name: "ボディバッグ/ウェストバッグ"},{category_name: "マザーズバッグ"},{category_name: "メッセンジャーバッグ"},{category_name: "ビジネスバッグ"},{category_name: "旅行用バッグ/キャリーバッグ"},{category_name: "ショップ袋"},{category_name: "和装用バッグ"},{category_name: "かごバッグ"},{category_name: "その他"}])
# lady_11 = lady.children.create(category_name: "アクセサリー")
# lady_11.children.create([{category_name: "ネックレス"},{category_name: "ブレスレット"},{category_name: "バングル/リストバンド"},{category_name: "リング"},{category_name: "ピアス(片耳用)"},{category_name: "ピアス(両耳用)"},{category_name: "イヤリング"},{category_name: "アンクレット"},{category_name: "ブローチ/コサージュ"},{category_name: "チャーム"},{category_name: "その他"}])
# lady_12 = lady.children.create(category_name: "ヘアアクセサリー")
# lady_12.children.create([{category_name: "ヘアゴム/シュシュ"},{category_name: "ヘアバンド/カチューシャ"},{category_name: "ヘアピン"},{category_name: "その他"}])
# lady_13 = lady.children.create(category_name: "小物")
# lady_13.children.create([{category_name: "長財布"},{category_name: "折り財布"},{category_name: "コインケース/小銭入れ"},{category_name: "名刺入れ/定期入れ"},{category_name: "キーケース"},{category_name: "キーホルダー"},{category_name: "手袋/アームカバー"},{category_name: "ハンカチ"},{category_name: "ベルト"},{category_name: "マフラー/ショール"},{category_name: "ストール/スヌード"},{category_name: "バンダナ/スカーフ"},{category_name: "ネックウォーマー"},{category_name: "サスペンダー"},{category_name: "サングラス/メガネ"},{category_name: "モバイルケース/カバー"},{category_name: "手帳"},{category_name: "イヤマフラー"},{category_name: "傘"},{category_name: "レインコート/ポンチョ"},{category_name: "ミラー"},{category_name: "タバコグッズ"},{category_name: "その他"}])
# lady_14 = lady.children.create(category_name: "時計")
# lady_14.children.create([{category_name: "腕時計(アナログ)"},{category_name: "腕時計(デジタル)"},{category_name: "ラバーベルト"},{category_name: "レザーベルト"},{category_name: "金属ベルト"},{category_name: "その他"}])
# lady_15 = lady.children.create(category_name: "ウィッグ/エクステ")
# lady_15.children.create([{category_name: "前髪ウィッグ"},{category_name: "ロングストレート"},{category_name: "ロングカール"},{category_name: "ショートストレート"},{category_name: "ショートカール"},{category_name: "その他"}])
# lady_16 = lady.children.create(category_name: "浴衣/水着")
# lady_16.children.create([{category_name: "浴衣"},{category_name: "着物"},{category_name: "振袖"},{category_name: "長襦袢/半襦袢"},{category_name: "水着セパレート"},{category_name: "水着ワンピース"},{category_name: "水着スポーツ用"},{category_name: "その他"}])
# lady_17 = lady.children.create(category_name: "スーツ/フォーマル/ドレス")
# lady_17.children.create([{category_name: "スカートスーツ上下"},{category_name: "パンツスーツ上下"},{category_name: "ドレス"},{category_name: "パーティーバッグ"},{category_name: "シューズ"},{category_name: "ウェディング"},{category_name: "その他"}])
# lady_18 = lady.children.create(category_name: "マタニティ")
# lady_18.children.create([{category_name: "トップス"},{category_name: "アウター"},{category_name: "インナー"},{category_name: "ワンピース"},{category_name: "パンツ/スパッツ"},{category_name: "スカート"},{category_name: "パジャマ"},{category_name: "授乳服"},{category_name: "その他"}])
# lady_19 = lady.children.create(category_name: "その他")
# lady_19.children.create([{category_name: "コスプレ"},{category_name: "下着"},{category_name: "その他"}])

# # メンズ
# men = Categori.create(category_name: "メンズ")
# men_1 = men.children.create(category_name: "トップス")
# men_1.children.create([{category_name: "Tシャツ/カットソー(半袖/袖なし)"},{category_name: "Tシャツ/カットソー(七分/長袖)"},{category_name: "シャツ"},{category_name: "ポロシャツ"},{category_name: "タンクトップ"},{category_name: "ニット/セーター"},{category_name: "パーカー"},{category_name: "カーディガン"},{category_name: "スウェット"},{category_name: "ジャージ"},{category_name: "ベスト"},{category_name: "その他"}])
# men_2 = men.children.create(category_name: "ジャケット/アウター")
# men_2.children.create([{category_name: "テーラードジャケット"},{category_name: "ノーカラージャケット"},{category_name: "Gジャン/デニムジャケット"},{category_name: "レザージャケット"},{category_name: "ダウンジャケット"},{category_name: "ライダースジャケット"},{category_name: "ミリタリージャケット"},{category_name: "ナイロンジャケット"},{category_name: "フライトジャケット"},{category_name: "ダッフルコート"},{category_name: "ピーコート"},{category_name: "ステンカラーコート"},{category_name: "トレンチコート"},{category_name: "モッズコート"},{category_name: "チェスターコート"},{category_name: "スタジャン"},{category_name: "スカジャン"},{category_name: "ブルゾン"},{category_name: "マウンテンパーカー"},{category_name: "ダウンベスト"},{category_name: "ポンチョ"},{category_name: "カバーオール"},{category_name: "その他"}])
# men_3 = men.children.create(category_name: "パンツ")
# men_3.children.create([{category_name: "デニム/ジーンズ"},{category_name: "ワークパンツ/カーゴパンツ"},{category_name: "スラックス"},{category_name: "チノパン"},{category_name: "ショートパンツ"},{category_name: "ペインターパンツ"},{category_name: "サルエルパンツ"},{category_name: "オーバーオール"},{category_name: "その他"}])
# men_4 = men.children.create(category_name: "靴")
# men_4.children.create([{category_name: "スニーカー"},{category_name: "サンダル"},{category_name: "ブーツ"},{category_name: "モカシン"},{category_name: "ドレス/ビジネス"},{category_name: "長靴/レインシューズ"},{category_name: "デッキシューズ"},{category_name: "その他"}])
# men_5 = men.children.create(category_name: "バッグ")
# men_5.children.create([{category_name: "ショルダーバッグ"},{category_name: "トートバッグ"},{category_name: "ボストンバッグ"},{category_name: "リュック/バックパック"},{category_name: "ウエストポーチ"},{category_name: "ボディーバッグ"},{category_name: "ドラムバッグ"},{category_name: "ビジネスバッグ"},{category_name: "トラベルバッグ"},{category_name: "メッセンジャーバッグ"},{category_name: "エコバッグ"},{category_name: "その他"}])
# men_6 = men.children.create(category_name: "スーツ")
# men_6.children.create([{category_name: "スーツジャケット"},{category_name: "スーツベスト"},{category_name: "スラックス"},{category_name: "セットアップ"},{category_name: "その他"}])
# men_7 = men.children.create(category_name: "帽子")
# men_7.children.create([{category_name: "キャップ"},{category_name: "ハット"},{category_name: "ニットキャップ/ビーニー"},{category_name: "ハンチング/ベレー帽"},{category_name: "キャスケット"},{category_name: "サンバイザー"},{category_name: "その他"}])
# men_8 = men.children.create(category_name: "アクセサリー")
# men_8.children.create([{category_name: "ネックレス"},{category_name: "ブレスレット"},{category_name: "バングル/リストバンド"},{category_name: "リング"},{category_name: "ピアス(片耳用)"},{category_name: "ピアス(両耳用)"},{category_name: "アンクレット"},{category_name: "その他"}])
# men_9 = men.children.create(category_name: "小物")
# men_9.children.create([{category_name: "長財布"},{category_name: "折り財布"},{category_name: "マネークリップ"},{category_name: "コインケース/小銭入れ"},{category_name: "名刺入れ/定期入れ"},{category_name: "キーケース"},{category_name: "キーホルダー"},{category_name: "ネクタイ"},{category_name: "手袋"},{category_name: "ハンカチ"},{category_name: "ベルト"},{category_name: "マフラー"},{category_name: "ストール"},{category_name: "バンダナ"},{category_name: "ネックウォーマー"},{category_name: "サスペンダー"},{category_name: "ウォレットチェーン"},{category_name: "サングラス/メガネ"},{category_name: "モバイルケース/カバー"},{category_name: "手帳"},{category_name: "ストラップ"},{category_name: "ネクタイピン"},{category_name: "カフリンクス"},{category_name: "イヤマフラー"},{category_name: "傘"},{category_name: "レインコート"},{category_name: "ミラー"},{category_name: "タバコグッズ"},{category_name: "その他"}])
# men_10 = men.children.create(category_name: "時計")
# men_10.children.create([{category_name: "腕時計(アナログ)"},{category_name: "腕時計(デジタル)"},{category_name: "ラバーベルト"},{category_name: "レザーベルト"},{category_name: "金属ベルト"},{category_name: "その他"}])
# men_11 = men.children.create(category_name: "水着")
# men_11.children.create([{category_name: "一般水着"},{category_name: "スポーツ用"},{category_name: "アクセサリー"},{category_name: "その他"}])
# men_12 = men.children.create(category_name: "レッグウェア")
# men_12.children.create([{category_name: "ソックス"},{category_name: "レギンス/スパッツ"},{category_name: "レッグウォーマー"},{category_name: "その他"}])
# men_13 = men.children.create(category_name: "アンダーウェア")
# men_13.children.create([{category_name: "トランクス"},{category_name: "ボクサーパンツ"},{category_name: "その他"}])
# men_14 = men.children.create(category_name: "その他")
# men_14.children.create([{category_name: "すべて"}])

# # ベビー・キッズ
# baby_kids = Categori.create(category_name: "ベビー・キッズ")
# baby_kids_1 = baby_kids.children.create(category_name: "ベビー服(女の子用) ~95cm")
# baby_kids_1.children.create([{category_name: "トップス"},{category_name: "アウター"},{category_name: "パンツ"},{category_name: "スカート"},{category_name: "ワンピース"},{category_name: "ベビードレス"},{category_name: "おくるみ"},{category_name: "下着/肌着"},{category_name: "パジャマ"},{category_name: "ロンパース"},{category_name: "その他"}])
# baby_kids_2 = baby_kids.children.create(category_name: "ベビー服(男の子用) ~95cm")
# baby_kids_2.children.create([{category_name: "トップス"},{category_name: "アウター"},{category_name: "パンツ"},{category_name: "おくるみ"},{category_name: "下着/肌着"},{category_name: "パジャマ"},{category_name: "ロンパース"},{category_name: "その他"}])
# baby_kids_3 = baby_kids.children.create(category_name: "ベビー服(男女兼用) ~95cm")
# baby_kids_3.children.create([{category_name: "トップス"},{category_name: "アウター"},{category_name: "パンツ"},{category_name: "おくるみ"},{category_name: "下着/肌着"},{category_name: "パジャマ"},{category_name: "ロンパース"},{category_name: "その他"}])
# baby_kids_4 = baby_kids.children.create(category_name: "キッズ服(女の子用) 100cm~")
# baby_kids_4.children.create([{category_name: "コート"},{category_name: "ジャケット/上着"},{category_name: "トップス(Tシャツ/カットソー)"},{category_name: "トップス(トレーナー)"},{category_name: "トップス(チュニック)"},{category_name: "トップス(タンクトップ)"},{category_name: "トップス(その他)"},{category_name: "スカート"},{category_name: "パンツ"},{category_name: "ワンピース"},{category_name: "セットアップ"},{category_name: "パジャマ"},{category_name: "フォーマル/ドレス"},{category_name: "和服"},{category_name: "浴衣"},{category_name: "甚平"},{category_name: "水着"},{category_name: "その他"}])
# baby_kids_5 = baby_kids.children.create(category_name: "キッズ服(男の子用) 100cm~")
# baby_kids_5.children.create([{category_name: "コート"},{category_name: "ジャケット/上着"},{category_name: "トップス(Tシャツ/カットソー)"},{category_name: "トップス(トレーナー)"},{category_name: "トップス(その他)"},{category_name: "パンツ"},{category_name: "セットアップ"},{category_name: "パジャマ"},{category_name: "フォーマル/ドレス"},{category_name: "和服"},{category_name: "浴衣"},{category_name: "甚平"},{category_name: "水着"},{category_name: "その他"}])
# baby_kids_6 = baby_kids.children.create(category_name: "キッズ服(男女兼用) 100cm~")
# baby_kids_6.children.create([{category_name: "コート"},{category_name: "ジャケット/上着"},{category_name: "トップス(Tシャツ/カットソー)"},{category_name: "トップス(トレーナー)"},{category_name: "トップス(その他)"},{category_name: "ボトムス"},{category_name: "パジャマ"},{category_name: "その他"}])
# baby_kids_7 = baby_kids.children.create(category_name: "キッズ靴")
# baby_kids_7.children.create([{category_name: "スニーカー"},{category_name: "サンダル"},{category_name: "ブーツ"},{category_name: "長靴"},{category_name: "その他"}])
# baby_kids_8 = baby_kids.children.create(category_name: "子ども用ファッション小物")
# baby_kids_8.children.create([{category_name: "靴下/スパッツ"},{category_name: "帽子"},{category_name: "エプロン"},{category_name: "サスペンダー"},{category_name: "タイツ"},{category_name: "ハンカチ"},{category_name: "バンダナ"},{category_name: "ベルト"},{category_name: "マフラー"},{category_name: "傘"},{category_name: "手袋"},{category_name: "スタイ"},{category_name: "バッグ"},{category_name: "その他"}])
# baby_kids_9 = baby_kids.children.create(category_name: "おむつ/トイレ/バス")
# baby_kids_9.children.create([{category_name: "おむつ用品"},{category_name: "おまる/補助便座"},{category_name: "トレーニングパンツ"},{category_name: "ベビーバス"},{category_name: "お風呂用品"},{category_name: "その他"}])
# baby_kids_10 = baby_kids.children.create(category_name: "外出/移動用品")
# baby_kids_10.children.create([{category_name: "ベビーカー"},{category_name: "抱っこひも/スリング"},{category_name: "チャイルドシート"},{category_name: "その他"}])
# baby_kids_11 = baby_kids.children.create(category_name: "授乳/食事")
# baby_kids_11.children.create([{category_name: "ミルク"},{category_name: "ベビーフード"},{category_name: "ベビー用食器"},{category_name: "その他"}])
# baby_kids_12 = baby_kids.children.create(category_name: "ベビー家具/寝具/室内用品")
# baby_kids_12.children.create([{category_name: "ベッド"},{category_name: "布団/毛布"},{category_name: "イス"},{category_name: "たんす"},{category_name: "その他"}])
# baby_kids_13 = baby_kids.children.create(category_name: "おもちゃ")
# baby_kids_13.children.create([{category_name: "おふろのおもちゃ"},{category_name: "がらがら"},{category_name: "オルゴール"},{category_name: "ベビージム"},{category_name: "手押し車/カタカタ"},{category_name: "知育玩具"},{category_name: "その他"}])
# baby_kids_14 = baby_kids.children.create(category_name: "行事/記念品")
# baby_kids_14.children.create([{category_name: "お宮参り用品"},{category_name: "お食い初め用品"},{category_name: "アルバム"},{category_name: "手形/足形"},{category_name: "その他"}])
# baby_kids_15 = baby_kids.children.create(category_name: "その他")
# baby_kids_15.children.create([{category_name: "母子手帳用品"},{category_name: "その他"}])

# # インテリア・住まい・小物
# interior_residence_accessory = Categori.create(category_name: "インテリア・住まい・小物")
# interior_residence_accessory_1 = interior_residence_accessory.children.create(category_name: "キッチン/食器")
# interior_residence_accessory_1.children.create([{category_name: "食器"},{category_name: "調理器具"},{category_name: "収納/キッチン雑貨"},{category_name: "弁当用品"},{category_name: "カトラリー(スプーン等)"},{category_name: "テーブル用品"},{category_name: "容器"},{category_name: "エプロン"},{category_name: "アルコールグッズ"},{category_name: "浄水機"},{category_name: "その他"}])
# interior_residence_accessory_2 = interior_residence_accessory.children.create(category_name: "ベッド/マットレス")
# interior_residence_accessory_2.children.create([{category_name: "セミシングルベッド"},{category_name: "シングルベッド"},{category_name: "セミダブルベッド"},{category_name: "ダブルベッド"},{category_name: "ワイドダブルベッド"},{category_name: "クイーンベッド"},{category_name: "キングベッド"},{category_name: "脚付きマットレスベッド"},{category_name: "マットレス"},{category_name: "すのこベッド"},{category_name: "ロフトベッド/システムベッド"},{category_name: "簡易ベッド/折りたたみベッド"},{category_name: "収納付き"},{category_name: "その他"}])
# interior_residence_accessory_3 = interior_residence_accessory.children.create(category_name: "ソファ/ソファベッド")
# interior_residence_accessory_3.children.create([{category_name: "ソファセット"},{category_name: "シングルソファ"},{category_name: "ラブソファ"},{category_name: "トリプルソファ"},{category_name: "オットマン"},{category_name: "コーナーソファ"},{category_name: "ビーズソファ/クッションソファ"},{category_name: "ローソファ/フロアソファ"},{category_name: "ソファベッド"},{category_name: "応接セット"},{category_name: "ソファカバー"},{category_name: "リクライニングソファ"},{category_name: "その他"}])
# interior_residence_accessory_4 = interior_residence_accessory.children.create(category_name: "椅子/チェア")
# interior_residence_accessory_4.children.create([{category_name: "一般"},{category_name: "スツール"},{category_name: "ダイニングチェア"},{category_name: "ハイバックチェア"},{category_name: "ロッキングチェア"},{category_name: "座椅子"},{category_name: "折り畳みイス"},{category_name: "デスクチェア"},{category_name: "その他"}])
# interior_residence_accessory_5 = interior_residence_accessory.children.create(category_name: "机/テーブル")
# interior_residence_accessory_5.children.create([{category_name: "こたつ"},{category_name: "カウンターテーブル"},{category_name: "サイドテーブル"},{category_name: "センターテーブル"},{category_name: "ダイニングテーブル"},{category_name: "座卓/ちゃぶ台"},{category_name: "アウトドア用"},{category_name: "パソコン用"},{category_name: "事務机/学習机"},{category_name: "その他"}])
# interior_residence_accessory_6 = interior_residence_accessory.children.create(category_name: "収納家具")
# interior_residence_accessory_6.children.create([{category_name: "リビング収納"},{category_name: "キッチン収納"},{category_name: "玄関/屋外収納"},{category_name: "バス/トイレ収納"},{category_name: "本収納"},{category_name: "本/CD/DVD収納"},{category_name: "洋服タンス/押入れ収納"},{category_name: "電話台/ファックス台"},{category_name: "ドレッサー/鏡台"},{category_name: "棚/ラック"},{category_name: "ケース/ボックス"},{category_name: "その他"}])
# interior_residence_accessory_7 = interior_residence_accessory.children.create(category_name: "ラグ/カーペット/マット")
# interior_residence_accessory_7.children.create([{category_name: "ラグ"},{category_name: "カーペット"},{category_name: "ホットカーペット"},{category_name: "玄関/キッチンマット"},{category_name: "トイレ/バスマット"},{category_name: "その他"}])
# interior_residence_accessory_8 = interior_residence_accessory.children.create(category_name: "カーテン/ブラインド")
# interior_residence_accessory_8.children.create([{category_name: "カーテン"},{category_name: "ブラインド"},{category_name: "ロールスクリーン"},{category_name: "のれん"},{category_name: "その他"}])
# interior_residence_accessory_9 = interior_residence_accessory.children.create(category_name: "ライト/照明")
# interior_residence_accessory_9.children.create([{category_name: "蛍光灯/電球"},{category_name: "天井照明"},{category_name: "フロアスタンド"},{category_name: "その他"}])
# interior_residence_accessory_10 = interior_residence_accessory.children.create(category_name: "寝具")
# interior_residence_accessory_10.children.create([{category_name: "布団/毛布"},{category_name: "枕"},{category_name: "シーツ/カバー"},{category_name: "その他"}])
# interior_residence_accessory_11 = interior_residence_accessory.children.create(category_name: "インテリア小物")
# interior_residence_accessory_11.children.create([{category_name: "ごみ箱"},{category_name: "ウェルカムボード"},{category_name: "オルゴール"},{category_name: "クッション"},{category_name: "クッションカバー"},{category_name: "スリッパラック"},{category_name: "ティッシュボックス"},{category_name: "バスケット/かご"},{category_name: "フォトフレーム"},{category_name: "マガジンラック"},{category_name: "モビール"},{category_name: "モビール"},{category_name: "花瓶"},{category_name: "灰皿"},{category_name: "傘立て"},{category_name: "小物入れ"},{category_name: "置時計"},{category_name: "掛時計/柱時計"},{category_name: "鏡(立て掛け式)"},{category_name: "鏡(壁掛け式)"},{category_name: "置物"},{category_name: "風鈴"},{category_name: "植物/観葉植物"},{category_name: "その他"}])
# interior_residence_accessory_12 = interior_residence_accessory.children.create(category_name: "季節/年中行事")
# interior_residence_accessory_12.children.create([{category_name: "正月"},{category_name: "成人式"},{category_name: "バレンタインデー"},{category_name: "ひな祭り"},{category_name: "子どもの日"},{category_name: "母の日"},{category_name: "父の日"},{category_name: "父の日"},{category_name: "サマーギフト/お中元"},{category_name: "夏/夏休み"},{category_name: "ハロウィン"},{category_name: "敬老の日"},{category_name: "七五三"},{category_name: "お歳暮"},{category_name: "クリスマス"},{category_name: "冬一般"},{category_name: "その他"}])
# interior_residence_accessory_13 = interior_residence_accessory.children.create(category_name: "その他")
# interior_residence_accessory_13.children.create([{category_name: "すべて"}])

# # 本・音楽・ゲーム
# book_music_game = Categori.create(category_name: "本・音楽・ゲーム")
# book_music_game_1 = book_music_game.children.create(category_name: "本")
# book_music_game_1.children.create([{category_name: "文学/小説"},{category_name: "人文/社会"},{category_name: "ノンフィクション/教養"},{category_name: "地図/旅行ガイド"},{category_name: "ビジネス/経済"},{category_name: "ビジネス/経済"},{category_name: "健康/医学"},{category_name: "コンピュータ/IT"},{category_name: "趣味/スポーツ/実用"},{category_name: "住まい/暮らし/子育て"},{category_name: "アート/エンタメ"},{category_name: "洋書"},{category_name: "絵本"},{category_name: "参考書"},{category_name: "その他"}])
# book_music_game_2 = book_music_game.children.create(category_name: "漫画")
# book_music_game_2.children.create([{category_name: "全巻セット"},{category_name: "少年漫画"},{category_name: "少女漫画"},{category_name: "青年漫画"},{category_name: "女性漫画"},{category_name: "同人誌"},{category_name: "その他"}])
# book_music_game_3 = book_music_game.children.create(category_name: "雑誌")
# book_music_game_3.children.create([{category_name: "アート/エンタメ/ホビー"},{category_name: "ファッション"},{category_name: "ニュース/総合"},{category_name: "趣味/スポーツ"},{category_name: "その他"}])
# book_music_game_4 = book_music_game.children.create(category_name: "CD")
# book_music_game_4.children.create([{category_name: "邦楽"},{category_name: "洋楽"},{category_name: "アニメ"},{category_name: "クラシック"},{category_name: "K-POP/アジア"},{category_name: "キッズ/ファミリー"},{category_name: "その他"}])
# book_music_game_5 = book_music_game.children.create(category_name: "DVD/ブルーレイ")
# book_music_game_5.children.create([{category_name: "外国映画"},{category_name: "日本映画"},{category_name: "アニメ"},{category_name: "TVドラマ"},{category_name: "ミュージック"},{category_name: "お笑い/バラエティ"},{category_name: "スポーツ/フィットネス"},{category_name: "キッズ/ファミリー"},{category_name: "その他"}])
# book_music_game_6 = book_music_game.children.create(category_name: "レコード")
# book_music_game_6.children.create([{category_name: "邦楽"},{category_name: "洋楽"},{category_name: "その他"}])
# book_music_game_7 = book_music_game.children.create(category_name: "テレビゲーム")
# book_music_game_7.children.create([{category_name: "家庭用ゲーム本体"},{category_name: "家庭用ゲームソフト"},{category_name: "携帯用ゲーム本体"},{category_name: "携帯用ゲームソフト"},{category_name: "PCゲーム"},{category_name: "その他"}])

# # おもちゃ・ホビー・グッズ
# toy_hobby_goods = Categori.create(category_name: "おもちゃ・ホビー・グッズ")
# toy_hobby_goods_1 = toy_hobby_goods.children.create(category_name: "おもちゃ")
# toy_hobby_goods_1.children.create([{category_name: "キャラクターグッズ"},{category_name: "ぬいぐるみ"},{category_name: "小物/アクセサリー"},{category_name: "模型/プラモデル"},{category_name: "ミニカー"},{category_name: "トイラジコン"},{category_name: "プラモデル"},{category_name: "ホビーラジコン"},{category_name: "鉄道模型"},{category_name: "その他"}])
# toy_hobby_goods_2 = toy_hobby_goods.children.create(category_name: "タレントグッズ")
# toy_hobby_goods_2.children.create([{category_name: "アイドル"},{category_name: "ミュージシャン"},{category_name: "タレント/お笑い芸人"},{category_name: "スポーツ選手"},{category_name: "その他"}])
# toy_hobby_goods_3 = toy_hobby_goods.children.create(category_name: "コミック/アニメグッズ")
# toy_hobby_goods_3.children.create([{category_name: "ストラップ"},{category_name: "キーホルダー"},{category_name: "バッジ"},{category_name: "カード"},{category_name: "クリアファイル"},{category_name: "ポスター"},{category_name: "タオル"},{category_name: "その他"}])
# toy_hobby_goods_4 = toy_hobby_goods.children.create(category_name: "トレーディングカード")
# toy_hobby_goods_4.children.create([{category_name: "遊戯王"},{category_name: "マジック：ザ・ギャザリング"},{category_name: "ポケモンカードゲーム"},{category_name: "デュエルマスターズ"},{category_name: "バトルスピリッツ"},{category_name: "プリパラ"},{category_name: "アイカツ"},{category_name: "カードファイト!! ヴァンガード"},{category_name: "ヴァイスシュヴァルツ"},{category_name: "プロ野球オーナーズリーグ"},{category_name: "ベースボールヒーローズ"},{category_name: "ドラゴンボール"},{category_name: "スリーブ"},{category_name: "その他"}])
# toy_hobby_goods_5 = toy_hobby_goods.children.create(category_name: "フィギュア")
# toy_hobby_goods_5.children.create([{category_name: "コミック/アニメ"},{category_name: "特撮"},{category_name: "ゲームキャラクター"},{category_name: "SF/ファンタジー/ホラー"},{category_name: "アメコミ"},{category_name: "スポーツ"},{category_name: "ミリタリー"},{category_name: "その他"}])
# toy_hobby_goods_6 = toy_hobby_goods.children.create(category_name: "楽器/器材")
# toy_hobby_goods_6.children.create([{category_name: "エレキギター"},{category_name: "アコースティックギター"},{category_name: "ベース"},{category_name: "エフェクター"},{category_name: "アンプ"},{category_name: "弦楽器"},{category_name: "管楽器"},{category_name: "鍵盤楽器"},{category_name: "打楽器"},{category_name: "和楽器"},{category_name: "楽譜/スコア"},{category_name: "レコーディング/PA機器"},{category_name: "DJ機器"},{category_name: "DTM/DAW"},{category_name: "その他"}])
# toy_hobby_goods_7 = toy_hobby_goods.children.create(category_name: "コレクション")
# toy_hobby_goods_7.children.create([{category_name: "武具"},{category_name: "使用済切手/官製はがき"},{category_name: "旧貨幣/金貨/銀貨/記念硬貨"},{category_name: "印刷物"},{category_name: "ノベルティグッズ"},{category_name: "その他"}])
# toy_hobby_goods_8 = toy_hobby_goods.children.create(category_name: "ミリタリー")
# toy_hobby_goods_8.children.create([{category_name: "トイガン"},{category_name: "個人装備"},{category_name: "その他"}])
# toy_hobby_goods_9 = toy_hobby_goods.children.create(category_name: "美術品")
# toy_hobby_goods_9.children.create([{category_name: "陶芸"},{category_name: "ガラス"},{category_name: "漆芸"},{category_name: "金属工芸"},{category_name: "絵画/タペストリ"},{category_name: "版画"},{category_name: "彫刻/オブジェクト"},{category_name: "書"},{category_name: "写真"},{category_name: "その他"}])
# toy_hobby_goods_10 = toy_hobby_goods.children.create(category_name: "アート用品")
# toy_hobby_goods_10.children.create([{category_name: "画材"},{category_name: "額縁"},{category_name: "その他"}])
# toy_hobby_goods_11 = toy_hobby_goods.children.create(category_name: "その他")
# toy_hobby_goods_11.children.create([{category_name: "トランプ/UNO"},{category_name: "カルタ/百人一首"},{category_name: "ダーツ"},{category_name: "ビリヤード"},{category_name: "麻雀"},{category_name: "パズル/ジグソーパズル"},{category_name: "囲碁/将棋"},{category_name: "オセロ/チェス"},{category_name: "人生ゲーム"},{category_name: "野球/サッカーゲーム"},{category_name: "スポーツ"},{category_name: "三輪車/乗り物"},{category_name: "ヨーヨー"},{category_name: "模型製作用品"},{category_name: "鉄道"},{category_name: "航空機"},{category_name: "アマチュア無線"},{category_name: "パチンコ/パチスロ"},{category_name: "その他"}])

# # コスメ・香水・美容
# cosme_perfume_beauty = Categori.create(category_name: "コスメ・香水・美容")
# cosme_perfume_beauty_1 = cosme_perfume_beauty.children.create(category_name: "ベースメイク")
# cosme_perfume_beauty_1.children.create([{category_name: "ファンデーション"},{category_name: "化粧下地"},{category_name: "コントロールカラー"},{category_name: "BBクリーム"},{category_name: "CCクリーム"},{category_name: "コンシーラー"},{category_name: "フェイスパウダー"},{category_name: "トライアルセット/サンプル"},{category_name: "その他"}])
# cosme_perfume_beauty_2 = cosme_perfume_beauty.children.create(category_name: "メイクアップ")
# cosme_perfume_beauty_2.children.create([{category_name: "アイシャドウ"},{category_name: "口紅"},{category_name: "リップグロス"},{category_name: "リップライナー"},{category_name: "チーク"},{category_name: "フェイスカラー"},{category_name: "マスカラ"},{category_name: "アイライナー"},{category_name: "つけまつげ"},{category_name: "アイブロウペンシル"},{category_name: "パウダーアイブロウ"},{category_name: "眉マスカラ"},{category_name: "トライアルセット/サンプル"},{category_name: "メイク道具/化粧小物"},{category_name: "美顔用品/美顔ローラー"},{category_name: "その他"}])
# cosme_perfume_beauty_3 = cosme_perfume_beauty.children.create(category_name: "ネイルケア")
# cosme_perfume_beauty_3.children.create([{category_name: "ネイルカラー"},{category_name: "カラージェル"},{category_name: "ネイルベースコート/トップコート"},{category_name: "ネイルアート用品"},{category_name: "ネイルパーツ"},{category_name: "ネイルチップ/付け爪"},{category_name: "手入れ用具"},{category_name: "除光液"},{category_name: "その他"}])
# cosme_perfume_beauty_4 = cosme_perfume_beauty.children.create(category_name: "香水")
# cosme_perfume_beauty_4.children.create([{category_name: "香水(女性用)"},{category_name: "香水(男性用)"},{category_name: "ユニセックス"},{category_name: "ボディミスト"},{category_name: "その他"}])
# cosme_perfume_beauty_5 = cosme_perfume_beauty.children.create(category_name: "スキンケア/基礎化粧品")
# cosme_perfume_beauty_5.children.create([{category_name: "化粧水/ローション"},{category_name: "乳液/ミルク"},{category_name: "美容液"},{category_name: "フェイスクリーム"},{category_name: "洗顔料"},{category_name: "クレンジング/メイク落とし"},{category_name: "パック/フェイスマスク"},{category_name: "ジェル/ゲル"},{category_name: "ブースター/導入液"},{category_name: "アイケア"},{category_name: "リップケア"},{category_name: "トライアルセット/サンプル"},{category_name: "洗顔グッズ"},{category_name: "その他"}])
# cosme_perfume_beauty_6 = cosme_perfume_beauty.children.create(category_name: "ヘアケア")
# cosme_perfume_beauty_6.children.create([{category_name: "シャンプー"},{category_name: "トリートメント"},{category_name: "コンディショナー"},{category_name: "リンス"},{category_name: "スタイリング剤"},{category_name: "カラーリング剤"},{category_name: "ブラシ"},{category_name: "その他"}])
# cosme_perfume_beauty_7 = cosme_perfume_beauty.children.create(category_name: "ボディケア")
# cosme_perfume_beauty_7.children.create([{category_name: "オイル/クリーム"},{category_name: "ハンドクリーム"},{category_name: "ローション"},{category_name: "日焼け止め/サンオイル"},{category_name: "ボディソープ"},{category_name: "入浴剤"},{category_name: "制汗/デオドラント"},{category_name: "フットケア"},{category_name: "その他"}])
# cosme_perfume_beauty_8 = cosme_perfume_beauty.children.create(category_name: "オーラルケア")
# cosme_perfume_beauty_8.children.create([{category_name: "口臭防止/エチケット用品"},{category_name: "歯ブラシ"},{category_name: "その他"}])
# cosme_perfume_beauty_9 = cosme_perfume_beauty.children.create(category_name: "リラクゼーション")
# cosme_perfume_beauty_9.children.create([{category_name: "エッセンシャルオイル"},{category_name: "芳香器"},{category_name: "お香/香炉"},{category_name: "キャンドル"},{category_name: "リラクゼーショングッズ"},{category_name: "その他"}])
# cosme_perfume_beauty_10 = cosme_perfume_beauty.children.create(category_name: "ダイエット")
# cosme_perfume_beauty_10.children.create([{category_name: "ダイエット食品"},{category_name: "エクササイズ用品"},{category_name: "体重計"},{category_name: "体脂肪計"},{category_name: "その他"}])
# cosme_perfume_beauty_11 = cosme_perfume_beauty.children.create(category_name: "その他")
# cosme_perfume_beauty_11.children.create([{category_name: "健康用品"},{category_name: "看護/介護用品"},{category_name: "救急/衛生用品"},{category_name: "その他"}])

# # 家電・スマホ・カメラ
# appliance_smartphone_camera = Categori.create(category_name: "家電・スマホ・カメラ")
# appliance_smartphone_camera_1 = appliance_smartphone_camera.children.create(category_name: "スマートフォン/携帯電話")
# appliance_smartphone_camera_1.children.create([{category_name: "スマートフォン本体"},{category_name: "バッテリー/充電器"},{category_name: "携帯電話本体"},{category_name: "PHS本体"},{category_name: "その他"}])
# appliance_smartphone_camera_2 = appliance_smartphone_camera.children.create(category_name: "スマホアクセサリー")
# appliance_smartphone_camera_2.children.create([{category_name: "Android用ケース"},{category_name: "iPhone用ケース"},{category_name: "カバー"},{category_name: "イヤホンジャック"},{category_name: "ストラップ"},{category_name: "フィルム"},{category_name: "自撮り棒"},{category_name: "その他"}])
# appliance_smartphone_camera_3 = appliance_smartphone_camera.children.create(category_name: "PC/タブレット")
# appliance_smartphone_camera_3.children.create([{category_name: "タブレット"},{category_name: "ノートPC"},{category_name: "デスクトップ型PC"},{category_name: "ディスプレイ"},{category_name: "電子ブックリーダー"},{category_name: "PC周辺機器"},{category_name: "PCパーツ"},{category_name: "その他"}])
# appliance_smartphone_camera_4 = appliance_smartphone_camera.children.create(category_name: "カメラ")
# appliance_smartphone_camera_4.children.create([{category_name: "デジタルカメラ"},{category_name: "ビデオカメラ"},{category_name: "レンズ(単焦点)"},{category_name: "レンズ(ズーム)"},{category_name: "フィルムカメラ"},{category_name: "防犯カメラ"},{category_name: "その他"}])
# appliance_smartphone_camera_5 = appliance_smartphone_camera.children.create(category_name: "テレビ/映像機器")
# appliance_smartphone_camera_5.children.create([{category_name: "テレビ"},{category_name: "プロジェクター"},{category_name: "ブルーレイレコーダー"},{category_name: "DVDレコーダー"},{category_name: "ブルーレイプレーヤー"},{category_name: "DVDプレーヤー"},{category_name: "映像用ケーブル"},{category_name: "その他"}])
# appliance_smartphone_camera_6 = appliance_smartphone_camera.children.create(category_name: "オーディオ機器")
# appliance_smartphone_camera_6.children.create([{category_name: "ポータブルプレーヤー"},{category_name: "イヤフォン"},{category_name: "ヘッドフォン"},{category_name: "アンプ"},{category_name: "スピーカー"},{category_name: "ケーブル/シールド"},{category_name: "ラジオ"},{category_name: "その他"}])
# appliance_smartphone_camera_7 = appliance_smartphone_camera.children.create(category_name: "美容/健康")
# appliance_smartphone_camera_7.children.create([{category_name: "ヘアドライヤー"},{category_name: "ヘアアイロン"},{category_name: "美容機器"},{category_name: "電気シェーバー"},{category_name: "電動歯ブラシ"},{category_name: "その他"}])
# appliance_smartphone_camera_8 = appliance_smartphone_camera.children.create(category_name: "冷暖房/空調")
# appliance_smartphone_camera_8.children.create([{category_name: "エアコン"},{category_name: "空気清浄器"},{category_name: "加湿器"},{category_name: "扇風機"},{category_name: "除湿機"},{category_name: "ファンヒーター"},{category_name: "電気ヒーター"},{category_name: "オイルヒーター"},{category_name: "ストーブ"},{category_name: "ホットカーペット"},{category_name: "こたつ"},{category_name: "電気毛布"},{category_name: "その他"}])
# appliance_smartphone_camera_9 = appliance_smartphone_camera.children.create(category_name: "生活家電")
# appliance_smartphone_camera_9.children.create([{category_name: "冷蔵庫"},{category_name: "洗濯機"},{category_name: "炊飯器"},{category_name: "電子レンジ/オーブン"},{category_name: "調理機器"},{category_name: "アイロン"},{category_name: "掃除機"},{category_name: "エスプレッソマシン"},{category_name: "コーヒーメーカー"},{category_name: "衣類乾燥機"},{category_name: "その他"}])
# appliance_smartphone_camera_10 = appliance_smartphone_camera.children.create(category_name: "その他")
# appliance_smartphone_camera_10.children.create([{category_name: "その他"}])
# # スポーツ・レジャー
# sport_leisure = Categori.create(category_name: "スポーツ・レジャー")
# sport_leisure_1 = sport_leisure.children.create(category_name: "ゴルフ")
# sport_leisure_1.children.create([{category_name: "クラブ"},{category_name: "ウエア(男性用)"},{category_name: "ウエア(女性用)"},{category_name: "バッグ"},{category_name: "シューズ(男性用)"},{category_name: "シューズ(女性用)"},{category_name: "アクセサリー"},{category_name: "その他"}])
# sport_leisure_2 = sport_leisure.children.create(category_name: "フィッシング")
# sport_leisure_2.children.create([{category_name: "ロッド"},{category_name: "リール"},{category_name: "ルアー用品"},{category_name: "ウエア"},{category_name: "釣り糸/ライン"},{category_name: "その他"}])
# sport_leisure_3 = sport_leisure.children.create(category_name: "自転車")
# sport_leisure_3.children.create([{category_name: "自転車本体"},{category_name: "ウエア"},{category_name: "パーツ"},{category_name: "アクセサリー"},{category_name: "バッグ"},{category_name: "工具/メンテナンス"},{category_name: "その他"}])
# sport_leisure_4 = sport_leisure.children.create(category_name: "トレーニング/エクササイズ")
# sport_leisure_4.children.create([{category_name: "ランニング"},{category_name: "ウォーキング"},{category_name: "ヨガ"},{category_name: "トレーニング用品"},{category_name: "その他"}])
# sport_leisure_5 = sport_leisure.children.create(category_name: "野球")
# sport_leisure_5.children.create([{category_name: "ウェア"},{category_name: "シューズ"},{category_name: "グローブ"},{category_name: "バット"},{category_name: "アクセサリー"},{category_name: "防具"},{category_name: "練習機器"},{category_name: "記念グッズ"},{category_name: "応援グッズ"},{category_name: "その他"}])
# sport_leisure_6 = sport_leisure.children.create(category_name: "サッカー/フットサル")
# sport_leisure_6.children.create([{category_name: "ウェア"},{category_name: "シューズ"},{category_name: "ボール"},{category_name: "アクセサリー"},{category_name: "記念グッズ"},{category_name: "応援グッズ"},{category_name: "その他"}])
# sport_leisure_7 = sport_leisure.children.create(category_name: "テニス")
# sport_leisure_7.children.create([{category_name: "ラケット(硬式用)"},{category_name: "ラケット(軟式用)"},{category_name: "ウェア"},{category_name: "シューズ"},{category_name: "ボール"},{category_name: "アクセサリー"},{category_name: "記念グッズ"},{category_name: "応援グッズ"},{category_name: "その他"}])
# sport_leisure_8 = sport_leisure.children.create(category_name: "スノーボード")
# sport_leisure_8.children.create([{category_name: "ボード"},{category_name: "バインディング"},{category_name: "ブーツ(男性用)"},{category_name: "ブーツ(女性用)"},{category_name: "ブーツ(子ども用)"},{category_name: "ウエア/装備(男性用)"},{category_name: "ウエア/装備(女性用)"},{category_name: "ウエア/装備(子ども用)"},{category_name: "アクセサリー"},{category_name: "バッグ"},{category_name: "その他"}])
# sport_leisure_9 = sport_leisure.children.create(category_name: "スキー")
# sport_leisure_9.children.create([{category_name: "板"},{category_name: "ブーツ(男性用)"},{category_name: "ブーツ(女性用)"},{category_name: "ブーツ(子ども用)"},{category_name: "ビンディング"},{category_name: "ウエア(男性用)"},{category_name: "ウエア(女性用)"},{category_name: "ウエア(子ども用)"},{category_name: "ストック"},{category_name: "その他"}])
# sport_leisure_10 = sport_leisure.children.create(category_name: "その他スポーツ")
# sport_leisure_10.children.create([{category_name: "ダンス/バレエ"},{category_name: "サーフィン"},{category_name: "バスケットボール"},{category_name: "バドミントン"},{category_name: "バレーボール"},{category_name: "スケートボード"},{category_name: "陸上競技"},{category_name: "ラグビー"},{category_name: "アメリカンフットボール"},{category_name: "ボクシング"},{category_name: "ボウリング"},{category_name: "その他"}])
# sport_leisure_11 = sport_leisure.children.create(category_name: "アウトドア")
# sport_leisure_11.children.create([{category_name: "テント/タープ"},{category_name: "ライト/ランタン"},{category_name: "寝袋/寝具"},{category_name: "テーブル/チェア"},{category_name: "ストーブ/コンロ"},{category_name: "調理器具"},{category_name: "食器"},{category_name: "登山用品"},{category_name: "その他"}])
# sport_leisure_12 = sport_leisure.children.create(category_name: "その他")
# sport_leisure_12.children.create([{category_name: "旅行用品"},{category_name: "その他"}])

# # ハンドメイド
# handmade = Categori.create(category_name: "ハンドメイド")
# handmade_1 = handmade.children.create(category_name: "アクセサリー(女性用)")
# handmade_1.children.create([{category_name: "ピアス"},{category_name: "イヤリング"},{category_name: "ネックレス"},{category_name: "ブレスレット"},{category_name: "リング"},{category_name: "チャーム"},{category_name: "ヘアゴム"},{category_name: "アンクレット"},{category_name: "その他"}])
# handmade_2 = handmade.children.create(category_name: "ファッション/小物")
# handmade_2.children.create([{category_name: "バッグ(女性用)"},{category_name: "バッグ(男性用)"},{category_name: "財布(女性用)"},{category_name: "財布(男性用)"},{category_name: "ファッション雑貨"},{category_name: "その他"}])
# handmade_3 = handmade.children.create(category_name: "アクセサリー/時計")
# handmade_3.children.create([{category_name: "アクセサリー(男性用)"},{category_name: "時計(女性用)"},{category_name: "時計(男性用)"},{category_name: "その他"}])
# handmade_4 = handmade.children.create(category_name: "日用品/インテリア")
# handmade_4.children.create([{category_name: "キッチン用品"},{category_name: "家具"},{category_name: "文房具"},{category_name: "アート/写真"},{category_name: "アロマ/キャンドル"},{category_name: "フラワー/ガーデン"},{category_name: "その他"}])
# handmade_5 = handmade.children.create(category_name: "趣味/おもちゃ")
# handmade_5.children.create([{category_name: "クラフト/布製品"},{category_name: "おもちゃ/人形"},{category_name: "その他"}])
# handmade_6 = handmade.children.create(category_name: "キッズ/ベビー")
# handmade_6.children.create([{category_name: "ファッション雑貨"},{category_name: "スタイ/よだれかけ"},{category_name: "外出用品"},{category_name: "ネームタグ"},{category_name: "その他"}])
# handmade_7 = handmade.children.create(category_name: "素材/材料")
# handmade_7.children.create([{category_name: "各種パーツ"},{category_name: "生地/糸"},{category_name: "型紙/パターン"},{category_name: "その他"}])
# handmade_8 = handmade.children.create(category_name: "二次創作物")
# handmade_8.children.create([{category_name: "Ingress"},{category_name: "クリエイターズ宇宙兄弟"},{category_name: "その他"},{category_name: "チケット"},{category_name: "すべて"}])
# handmade_9 = handmade.children.create(category_name: "その他")
# handmade_9.children.create([{category_name: "すべて"}])

# # チケット
# ticket = Categori.create(category_name: "チケット")
# ticket_1 = ticket.children.create(category_name: "音楽")
# ticket_1.children.create([{category_name: "男性アイドル"},{category_name: "女性アイドル"},{category_name: "韓流"},{category_name: "国内アーティスト"},{category_name: "海外アーティスト"},{category_name: "音楽フェス"},{category_name: "声優/アニメ"},{category_name: "その他"}])
# ticket_2 = ticket.children.create(category_name: "スポーツ")
# ticket_2.children.create([{category_name: "サッカー"},{category_name: "野球"},{category_name: "テニス"},{category_name: "格闘技/プロレス"},{category_name: "相撲/武道"},{category_name: "ゴルフ"},{category_name: "バレーボール"},{category_name: "バスケットボール"},{category_name: "モータースポーツ"},{category_name: "ウィンタースポーツ"},{category_name: "その他"}])
# ticket_3 = ticket.children.create(category_name: "演劇/芸能")
# ticket_3.children.create([{category_name: "ミュージカル"},{category_name: "演劇"},{category_name: "伝統芸能"},{category_name: "落語"},{category_name: "お笑い"},{category_name: "オペラ"},{category_name: "サーカス"},{category_name: "バレエ"},{category_name: "その他"}])
# ticket_4 = ticket.children.create(category_name: "イベント")
# ticket_4.children.create([{category_name: "声優/アニメ"},{category_name: "キッズ/ファミリー"},{category_name: "トークショー/講演会"},{category_name: "その他"}])
# ticket_5 = ticket.children.create(category_name: "映画")
# ticket_5.children.create([{category_name: "邦画"},{category_name: "洋画"},{category_name: "その他"}])
# ticket_6 = ticket.children.create(category_name: "施設利用券")
# ticket_6.children.create([{category_name: "遊園地/テーマパーク"},{category_name: "美術館/博物館"},{category_name: "スキー場"},{category_name: "ゴルフ場"},{category_name: "フィットネスクラブ"},{category_name: "プール"},{category_name: "ボウリング場"},{category_name: "水族館"},{category_name: "動物園"},{category_name: "その他"}])
# ticket_7 = ticket.children.create(category_name: "優待券/割引券")
# ticket_7.children.create([{category_name: "ショッピング"},{category_name: "レストラン/食事券"},{category_name: "フード/ドリンク券"},{category_name: "宿泊券"},{category_name: "その他"}])
# ticket_8 = ticket.children.create(category_name: "その他")
# ticket_8.children.create([{category_name: "すべて"}])


# # 自動車・オートバイ
# car_motorcycle = Categori.create(category_name: "自動車・オートバイ")
# car_motorcycle_1 = car_motorcycle.children.create(category_name: "自動車本体")
# car_motorcycle_1.children.create([{category_name: "国内自動車本体"},{category_name: "外国自動車本体"}])
# car_motorcycle_2 = car_motorcycle.children.create(category_name: "自動車タイヤ/ホイール")
# car_motorcycle_2.children.create([{category_name: "タイヤ/ホイールセット"},{category_name: "タイヤ"},{category_name: "ホイール"},{category_name: "その他"}])
# car_motorcycle_3 = car_motorcycle.children.create(category_name: "自動車パーツ")
# car_motorcycle_3.children.create([{category_name: "サスペンション"},{category_name: "ブレーキ"},{category_name: "外装、エアロパーツ"},{category_name: "ライト"},{category_name: "内装品、シート"},{category_name: "ステアリング"},{category_name: "マフラー・排気系"},{category_name: "エンジン、過給器、冷却装置"},{category_name: "クラッチ、ミッション、駆動系"},{category_name: "電装品"},{category_name: "補強パーツ"},{category_name: "汎用パーツ"},{category_name: "外国自動車用パーツ"},{category_name: "その他"}])
# car_motorcycle_4 = car_motorcycle.children.create(category_name: "自動車アクセサリー")
# car_motorcycle_4.children.create([{category_name: "車内アクセサリー"},{category_name: "カーナビ"},{category_name: "カーオーディオ"},{category_name: "車外アクセサリー"},{category_name: "メンテナンス用品"},{category_name: "チャイルドシート"},{category_name: "ドライブレコーダー"},{category_name: "レーダー探知機"},{category_name: "カタログ/マニュアル"},{category_name: "セキュリティ"},{category_name: "ETC"},{category_name: "その他"}])
# car_motorcycle_5 = car_motorcycle.children.create(category_name: "オートバイ車体")
# car_motorcycle_5.children.create([{category_name: "すべて"}])
# car_motorcycle_6 = car_motorcycle.children.create(category_name: "オートバイパーツ")
# car_motorcycle_6.children.create([{category_name: "タイヤ"},{category_name: "マフラー"},{category_name: "エンジン、冷却装置"},{category_name: "カウル、フェンダー、外装"},{category_name: "サスペンション"},{category_name: "ホイール"},{category_name: "シート"},{category_name: "ブレーキ"},{category_name: "タンク"},{category_name: "ライト、ウィンカー"},{category_name: "チェーン、スプロケット、駆動系"},{category_name: "メーター"},{category_name: "電装系"},{category_name: "ミラー"},{category_name: "外国オートバイ用パーツ"},{category_name: "その他"}])
# car_motorcycle_7 = car_motorcycle.children.create(category_name: "オートバイアクセサリー")
# car_motorcycle_7.children.create([{category_name: "ヘルメット/シールド"},{category_name: "バイクウエア/装備"},{category_name: "アクセサリー"},{category_name: "メンテナンス"},{category_name: "カタログ/マニュアル"},{category_name: "その他"}])

# # その他
# others = Categori.create(category_name: "その他")
# others_1 = others.children.create(category_name: "まとめ売り")
# others_1.children.create([{category_name: "すべて"}])
# others_2 = others.children.create(category_name: "ペット用品")
# others_2.children.create([{category_name: "ペットフード"},{category_name: "犬用品"},{category_name: "猫用品"},{category_name: "魚用品/水草"},{category_name: "小動物用品"},{category_name: "爬虫類/両生類用品"},{category_name: "かご/おり"},{category_name: "鳥用品"},{category_name: "虫類用品"},{category_name: "その他"}])
# others_3 = others.children.create(category_name: "食品")
# others_3.children.create([{category_name: "菓子"},{category_name: "米"},{category_name: "野菜"},{category_name: "果物"},{category_name: "調味料"},{category_name: "魚介類(加工食品)"},{category_name: "肉類(加工食品)"},{category_name: "その他 加工食品"},{category_name: "その他"}])
# others_4 = others.children.create(category_name: "飲料/酒")
# others_4.children.create([{category_name: "コーヒー"},{category_name: "ソフトドリンク"},{category_name: "ミネラルウォーター"},{category_name: "茶"},{category_name: "ウイスキー"},{category_name: "ワイン"},{category_name: "ブランデー"},{category_name: "焼酎"},{category_name: "日本酒"},{category_name: "ビール、発泡酒"},{category_name: "その他"}])
# others_5 = others.children.create(category_name: "日用品/生活雑貨/旅行")
# others_5.children.create([{category_name: "タオル/バス用品"},{category_name: "日用品/生活雑貨"},{category_name: "洗剤/柔軟剤"},{category_name: "旅行用品"},{category_name: "防災関連グッズ"},{category_name: "その他"}])
# others_6 = others.children.create(category_name: "アンティーク/コレクション")
# others_6.children.create([{category_name: "雑貨"},{category_name: "工芸品"},{category_name: "家具"},{category_name: "印刷物"},{category_name: "その他"}])
# others_7 = others.children.create(category_name: "文房具/事務用品")
# others_7.children.create([{category_name: "筆記具"},{category_name: "ノート/メモ帳"},{category_name: "テープ/マスキングテープ"},{category_name: "カレンダー/スケジュール"},{category_name: "アルバム/スクラップ"},{category_name: "ファイル/バインダー"},{category_name: "はさみ/カッター"},{category_name: "カードホルダー/名刺管理"},{category_name: "のり/ホッチキス"},{category_name: "その他"}])
# others_8 = others.children.create(category_name: "事務/店舗用品")
# others_8.children.create([{category_name: "オフィス用品一般"},{category_name: "オフィス家具"},{category_name: "店舗用品"},{category_name: "OA機器"},{category_name: "ラッピング/包装"},{category_name: "その他"}])
# others_9 = others.children.create(category_name: "その他")
# others_9.children.create([{category_name: "すべて"}])